### ISSUE TITLE
Fix project discrepancies

### ISSUE THREAD

**Issue by NellyIfandieva** [Csharp-Team-Stamo/UpSkill#39]
1. Delete the ApiServer project along with any children
2. Create a Business Logic folder
3. Move UpSkill.Core and UpSkill.Infrastructure project within it 
4. Create Server folder
5. Create UpSkill.Api project within it
6. Create Tests
7. Move UpSkill..IntegrationTests within it

**Comment by martin-ali** [comment]
Completed
